name = "federation-supergraph-gateway"
main = "./dist/index.js"

compatibility_date = "2022-11-30"

services = [
  { binding = "subgraphLocationsService", service = "subgraph-locations" },
  { binding = "subgraphReviewsService", service = "subgraph-reviews" }
]

# [vars]
# GRAPHQL_PATH = "/graphql"

[build.upload]
format = "modules"

[miniflare]
route = "http://127.0.0.1/graphql*"
