name = "subgraph-locations"
main = "./dist/index.js"

compatibility_date = "2022-11-30"

# [vars]
# GRAPHQL_PATH = "/subgraph-locations"

[build.upload]
format = "modules"

# [miniflare]
# route = "http://127.0.0.1/subgraph-locations*"
